# Generated by Django 4.2.7 on 2023-12-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('IDESTACION', models.IntegerField(primary_key=True, serialize=False)),
                ('DENOMINACION', models.CharField(max_length=255)),
                ('LINEAS', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
    ]
