# Generated by Django 4.2.7 on 2023-12-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_savedstops_savedbicimad'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='ACONDICIONAMIENTOVIAJEROS',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
